fix: buildGo124Module already sets -buildmode=pie
buildGo124Module internally sets GOFLAGS with certain default
values (including -buildmode=pie -mod=vendor -trimpath),
and the derivation is trying to override it directly which creates a
conflict with the new Nix restriction.

`(stack trace truncated; use '--show-trace' to show the full, detailed trace)
    error: The `env` attribute set cannot contain any attributes passed to derivation. The following attributes are overlapping:
     - GOFLAGS: in `env`: "-buildmode=pie -mod=vendor -trimpath"; in derivation arguments: [
     "-buildmode=pie"
]`

Signed-off-by: Brian McGillion <bmg.avoin@gmail.com>